# roles/docker/tasks/main.yml
---
- name: Install prerequisites for Docker
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'gnupg', 'lsb-release']
    state: present
  become: true

- name: Add Docker’s official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true

- name: Add Docker APT repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    state: present
  become: true

- name: Update package cache
  apt:
    update_cache: yes
  become: true

- name: Install Docker and Docker Compose
  apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-compose-plugin']
    state: present
  become: true

- name: Start and enable Docker service
  systemd:
    name: docker
    enabled: true
    state: started
  become: true
