---
- name: Install Python and pip on dev_vm
  hosts: dev_vms
  tasks:
    - name: Update package list
      apt:
        update_cache: yes

    - name: Install Python3 and pip3
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip
